// constants/projects.ts
export const Projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description:
      "an online store with cart functinality, calculations and live update. ",
    image: "/projects/ecommerce.jpg",
    tags: ["Web", "SaaS"],
    tech: ["JavaScript", "css", "html"],
    liveUrl: "#",
    codeUrl: "#",
  },
  {
    id: 2,
    title: "Habit tracking App",
    description:
      " habits and activity management app with comparison charts and graphs",
    image: "/projects/taskapp.jpg",
    tags: ["Web", "Mobile"],
    tech: ["React", "TailwindCSS", "ReCharts"],
    liveUrl: "#",
    codeUrl: "#",
  },
  {
    id: 3,
    title: "Portfolio Website",
    description: "Modern responsive portfolio with 3D elements",
    image: "/projects/portfolio.jpg",
    tags: ["Web"],
    tech: ["React", "Three.js", "GSAP"],
    liveUrl: "#",
    codeUrl: "#",
  },
  {
    id: 4,
    title: "Health Tracker",
    description: "Mobile app for tracking fitness and nutrition",
    image: "/projects/health.jpg",
    tags: ["Mobile"],
    tech: ["Flutter", "Firebase", "BLoC"],
    liveUrl: "#",
    codeUrl: "#",
  },
  {
    id: 5,
    title: "Open Source Library",
    description: "React component library for UI elements",
    image: "/projects/library.jpg",
    tags: ["Web", "Open Source"],
    tech: ["React", "TypeScript", "Storybook"],
    liveUrl: "#",
    codeUrl: "#",
  },
  {
    id: 6,
    title: "AI Chatbot",
    description: "Customer support chatbot with NLP",
    image: "/projects/chatbot.jpg",
    tags: ["SaaS"],
    tech: ["Python", "TensorFlow", "React"],
    liveUrl: "#",
    codeUrl: "#",
  },
];
