export const technologies = [
  // Frontend
  {
    name: "React",
    category: "Frontend",
    icon: "⚛️",
    color: "from-pink-400 to-pink-600",
    description: "Component-based UI library",
  },
  {
    name: "Next.js",
    category: "Frontend",
    icon: "▲",
    color: "from-blue-500 to-blue-700",
    description: "Full-stack React framework",
  },
  {
    name: "TypeScript",
    category: "Frontend",
    icon: "TS",
    color: "from-blue-500 to-blue-700",
    description: "Typed JavaScript",
  },
  {
    name: "Tailwind CSS",
    category: "Frontend",
    icon: "🎨",
    color: "from-cyan-400 to-cyan-600",
    description: "Utility-first CSS framework",
  },
  // {
  //   name: "Vue.js",
  //   category: "Frontend",
  //   icon: "🖖",
  //   color: "from-green-400 to-green-600",
  //   description: "Progressive JavaScript framework",
  // },
  // {
  //   name: "Sass",
  //   category: "Frontend",
  //   icon: "💎",
  //   color: "from-pink-400 to-pink-600",
  //   description: "CSS preprocessor",
  // },

  // Backend
  {
    name: "Node.js",
    category: "Backend",
    icon: "🟢",
    color: "from-green-500 to-green-700",
    description: "JavaScript runtime",
  },
  {
    name: "Python",
    category: "Backend",
    icon: "🐍",
    color: "from-green-400 to-blue-500",
    description: "Versatile programming language",
  },
  {
    name: "Express.js",
    category: "Backend",
    icon: "🚀",
    color: "from-blue-600 to-red-800",
    description: "Fast Node.js web framework",
  },
  // {
  //   name: "Django",
  //   category: "Backend",
  //   icon: "🎯",
  //   color: "from-green-600 to-green-800",
  //   description: "Python web framework",
  // },
  // {
  //   name: "GraphQL",
  //   category: "Backend",
  //   icon: "🔗",
  //   color: "from-pink-500 to-purple-600",
  //   description: "Query language for APIs",
  // },
  {
    name: "REST API",
    category: "Backend",
    icon: "🌐",
    color: "from-cyan-400 to-blue-600",
    description: "RESTful web services",
  },

  // Database
  {
    name: "MongoDB",
    category: "Database",
    icon: "🍃",
    color: "from-green-500 to-green-700",
    description: "NoSQL database",
  },
  // {
  //   name: "PostgreSQL",
  //   category: "Database",
  //   icon: "🐘",
  //   color: "from-blue-600 to-blue-800",
  //   description: "Relational database",
  // },
  // {
  //   name: "Redis",
  //   category: "Database",
  //   icon: "📦",
  //   color: "from-red-500 to-red-700",
  //   description: "In-memory data store",
  // },
  // {
  //   name: "Firebase",
  //   category: "Database",
  //   icon: "🔥",
  //   color: "from-yellow-400 to-orange-500",
  //   description: "Google cloud platform",
  // },

  // DevOps & Tools
  // {
  //   name: "Docker",
  //   category: "DevOps",
  //   icon: "🐳",
  //   color: "from-blue-400 to-blue-600",
  //   description: "Containerization platform",
  // },
  // {
  //   name: "AWS",
  //   category: "DevOps",
  //   icon: "☁️",
  //   color: "from-orange-400 to-yellow-500",
  //   description: "Cloud computing services",
  // },
  // {
  //   name: "Git",
  //   category: "DevOps",
  //   icon: "📚",
  //   color: "from-orange-500 to-red-500",
  //   description: "Version control system",
  // },
  // {
  //   name: "Kubernetes",
  //   category: "DevOps",
  //   icon: "⚓",
  //   color: "from-blue-600 to-purple-600",
  //   description: "Container orchestration",
  // },
  {
    name: "GSAP",
    category: "Design",
    icon: "🦸",
    color: "from-blue-400 to-yellow-500",
    description: "Animation and micro-interaction library",
  },
  {
    name: "Canva",
    category: "Design",
    icon: "✨",
    color: "from-yellow-600 to-orange-600",
    description: "Design and templating",
  },
  {
    name: "Framer Motion",
    category: "Design",
    icon: "🎞️",
    color: "from-purple-600 to-blue-600",
    description: "Animation library",
  },
  // non tech
  {
    name: "Public Speaking",
    category: "Non-Tech",
    icon: "🎤",
    color: "from-purple-600 to-blue-600",
    description: "effective storytelling and communication",
  },
  {
    name: "Problem Solving",
    category: "Non-Tech",
    icon: "🧩",
    color: "from-green-500 to-green-500",
    description: "Analytical and critical thinking",
  },
  {
    name: "Teamwork",
    category: "Non-Tech",
    icon: "🤝",
    color: "from-yellow-400 to-orange-500",
    description: "Collaboration and Leadership",
  },
  {
    name: "Event Management",
    category: "Non-Tech",
    icon: "⏳",
    color: "from-blue-400 to-cyan-500",
    description: "On-ground activity, prioritization and organization",
  },
  {
    name: "Leadership",
    category: "Non-Tech",
    icon: "",
    color: "from-blue-400 to-cyan-500",
    description: "On-ground activity, prioritization and organization",
  },
];

export const categories = [
  "All",
  "Frontend",
  "Backend",
  "Database",
  //"DevOps",
  "Design",
  "Non-Tech",
];
